# path of the design verilog file
circuit_file: circuits/adder.v
circuit_name: adder

# target delay of the circuit
target_delay: 2000

# standard cell library mapping
library_file: libraries/asap7_short.genlib

# available optimizaction actions
optimizations:
  mig:
    - rewrite
    - rewrite -azg
    - rewrite -udc
    - rewrite -pd
    - rewrite -azg -udc
    - rewrite -azg -pd
    - rewrite -udc -pd
    - rewrite -azg -udc -pd
    - balance
    - balance -c
    #- refactor
    #- refactor -azg
    #- refactor -udc
    #- refactor -azg -udc
    - resub
    - resub -pd
  aig:
    - rewrite
    - rewrite -z
    - refactor
    - refactor -z
    - resub
    - resub -z
    - balance

# only for Mockturtle relevant
mockturtle:
  graph_type: mig

# agent training parameters
train_iterations: 50
delay_reward_factor: 10
use_graph: False
preprocessor_pref: null # null = no preprocessing
MAX_STEPS: 50