# path of the design verilog file
circuit_file: circuits/hypo.v
circuit_name: hypo

# target delay of the circuit
target_delay: 1000000

# standard cell library mapping
library_file: libraries/asap7.lib

# available optimizaction actions
optimizations:
  mig:
    - rewrite
    - rewrite -udc
    - rewrite -azg
    - rewrite -udc -azg
    - balance
    - balance -c
  aig:
    - rewrite
    - rewrite -z
    - refactor
    - refactor -z
    - resub
    - resub -z
    - balance

# agent training parameters
train_iterations: 50
delay_reward_factor: 10
use_graph: False
preprocessor_pref: null # null = no preprocessing
MAX_STEPS: 50