# path of the design verilog file
circuit_file: circuits/max.v
circuit_name: max

# target delay of the circuit
target_delay: 4000

# standard cell library mapping
library_file: libraries/asap7.lib

# available optimizaction actions
optimizations:
  mig:
    - rewrite
    - rewrite -azg
    - rewrite -udc
    - rewrite -pd
    - rewrite -azg -udc
    - rewrite -azg -pd
    - rewrite -udc -pd
    - rewrite -azg -udc -pd
    - balance
    - balance -c
    #- refactor
    #- refactor -azg
    #- refactor -udc
    #- refactor -azg -udc
    - resub
    - resub -pd
  aig:
    - rewrite
    - rewrite -z
    - refactor
    - refactor -z
    - resub
    - resub -z
    - balance
    # - resub -K 8
    - dc2
    - ifraig
    - dch -f; dc2
    - dch -f; if -g
    - if -g

# only for Mockturtle relevant
mockturtle:
  graph_type: mig

# agent training parameters
env: Abc_Env  # Abc_Env or Mockturtle_Env
special_tag: lstm_replication
train_iterations: 50
delay_reward_factor: 10
use_graph: True
use_previous_action: True
preprocessor_pref: null # null = no preprocessing
MAX_STEPS: 40